

server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mapper:
  notEmpty: true
  identity: MYSQL


mybatis:
  mapperLocations: classpath:**/mapper/*.xml

logging:
  level:
    com:
      example:
        tkmapper:
          mapper: debug